// GENERATED by phone/build_exercises.py -- do not edit by hand.
// Source: the signatures of axcel.orientation.is_stationary and
// find_static_block. The phone re-implements the *test* (a few lines of
// rolling variance); it must never re-type the *numbers*, or the green
// light at the machine stops meaning what the analysis will accept.
export const ACCEL_TOL = 0.12;        // m/s^2
export const GYRO_TOL_DPS = 1.5;     // deg/s
export const WINDOW_S = 0.1;          // seconds per test window

// find_static_block needs this much CONTIGUOUS stillness. A light that went
// green on a single still window would have shown green on the set that was
// lost -- it had 9 still windows in its first 6 s and no run long enough.
export const MIN_STATIC_S = 0.4;       // seconds
